[package]
name = "web"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
axum = "0.8.4"
anyhow = "1.0.99"
sqlx = { version = "0.8.6", features = ["runtime-tokio","sqlite"] }
